### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/cwp-theme-default#1]
This repository is meant to be used with CWP 1.6 which has been end-of-lifed. 

We should marked this packaged has abandonned, maybe add a read me telling people not to use it and archived the repo.

# Pull Requests
* [x] #2

**Comment by maxime-rainville** [comment]
For reference https://www.cwp.govt.nz/working-with-cwp/#maintain

**Comment by dhensby** [comment]
Let's do it ;)

**Comment by maxime-rainville** [comment]
Got a PR to add a Readme. #2
